nodeLinker: pnp

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.5.0.cjs

packageExtensions:
  "styled-components@*":
    dependencies:
      "babel-plugin-macros": "*"
  "@types/express@*":
    dependencies:
      "serve-static": "*"
      "body-parser": "*"
      "qs": "*"
  "@types/express-serve-static-core@*":
    dependencies:
      "send": "*"
      "qs": "*"
      "events": "*"
      "range-parser": "*"
  "@types/send@*":
    dependencies:
      "mime": "*"
  "@types/serve-static@*":
    dependencies:
      "mime": "*"
  "@types/node@*":
    dependencies:
      "events": "*"
  "@lerna/legacy-package-management@*":
    dependencies:
      "@lerna/child-process": "*"
      "js-yaml": "*"
      "rimraf": "*"
